### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**

### CODE REVIEW

**Review by Mirsario — CHANGES_REQUESTED** [review]
> `Camera review settings`
> `Roll factor during firing`

This seems like a poor machine translation done with no human review involved.

**Comment by mpustovoi** [comment]
> > `Camera review settings`
> > `Roll factor during firing`
> 
> This seems like a poor machine translation done with no human review involved.

The most popular translation of "overhaul" into Russian is "major repairs", which makes very little sense in this context, but it has many other ways of translating.
image

The term "strafing", I suppose, refers to aviation, which I don't understand at all. There are two translations of this word in Russian: literally "shelling, firing, shooting, etc." and "low-level flight". I just chose the option that is more often used.
image
But to be honest, neither one nor the other translation option makes sense to me, as I don't understand such aviation terms that deeply.
I can change this to "low-level flight", but I still won't be 100% sure of the correctness. I hope there will be an aviator in the future

**Comment by Mirsario** [comment]
- Strafing means going sideways, via A/D keys in any first person game.
- "Camera Overhaul" is a title, so it's best just left in English.
- There's no relation to aviation terms anywhere, and looks like pitch & roll is translated using some? May be preferable to translate using word pairs such as `forward tilt` & `sideways tilt/roll`. "Yaw delta roll factor" refers to the strength of the sideways tilting (Z axis) that the camera gets when there's changes in camera's yaw (player turns sideways by moving the mouse horizontally). Similar lines follow the same logic.

**Comment by mpustovoi** [comment]
Thanks a lot for the clarification and new experience.
I'll apply the necessary changes.
Although in general it seems that the terms "roll", "pitch" and "yaw" are more commonly used in Russian (especially "roll") than "strafing" due to not having a direct analogue, for simplicity maybe I'll replace them with a tilt in the direction.

**Comment by mpustovoi** [comment]
Usually these three terms are directly translated, so I'll probably leave them as they are. The only word that can confuse here is "pitch", but after one search on the Internet, everything will become clear forever.

**Review by Mirsario — APPROVED** [review]
Fair enough, thanks.

**Pull request merged**
